---
- stat:
    shell: >
      docker info | egrep '^Swarm: ' | cut -d ' ' -f2
    register: swarm_status

- name: initialize swarm cluster
  host: master
  shell: >
    docker swarm init --advertise-addr={{ansible_eth0.ipv4.address}}

- name: retrieve swarm worker token
  host: master
  shell: docker swarm join-token -q worker
  register: swarm_worker_token
  when: "'active' not in swarm_status.stdout_lines"

- name: join worker node to cluster
  host: slave
  shell: >
    docker swarm join
    --advertise-addr={{ansible_eth0.ipv4.address}}
    --token={{ swarm_worker_token }}
    {{ groups["master"][0] }}
  when: "'active' not in swarm_status.stdout_lines"
