---
- stat:
    shell: >
      docker info | egrep '^Swarm: ' | cut -d ' ' -f2
    register: swarm_status

- block:
  - name: initialize swarm cluster
    shell: >
      docker swarm init --advertise-addr={{ansible_eth0.ipv4.address}}
  - name: retrieve swarm worker token
    shell: docker swarm join-token -q worker
    register: swarm_worker_token
  become: true
  become_user: root
  when: "'active' not in swarm_status.stdout_lines"


- block:
  - name: join worker node to cluster
    shell: >
      docker swarm join
      --advertise-addr={{ansible_eth0.ipv4.address}}
      --token={{ swarm_worker_token }}
      {{ groups["master"][0] }}
  become: true
  become_user: root
  when: "'active' not in swarm_status.stdout_lines"
