---
consul_version: "0.8.3"
consul_install_path: /usr/local/consul
consul_dc: pi
consul_dns_domain: pi.local
consul_client: "{{ ansible_eth0.ipv4.address }}"
consul_bind: "{{ ansible_eth0.ipv4.address }}"
consul_advertise: "{{ ansible_eth0.ipv4.address }}"
consul_is_server: "{% if ansible_hostname == 'master'}"
consul_retry_join: "{% for host in groups['pi'] %}\"{{ host }}\"{% if not loop.last %}, {% endif %}{% endfor %}"
consul_bootstrap_expect: 3
consul_disable_remote_exec: "true"
