---
###############################################################################
################################# INSTALL #####################################
###############################################################################
- stat:
    path: "{{ nomad_install_path }}/{{ nomad_version }}/"
  register: preexisting
  tags:
    - nomad

- name: download nomad
  get_url:
    url: "https://releases.hashicorp.com/nomad/{{ nomad_version }}/nomad_{{ nomad_version }}_linux_arm.zip"
    dest: /tmp/nomad.zip
    mode: 0777
  tags:
    - nomad

- name: create the install paths
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - "{{ nomad_install_path }}/{{ nomad_version }}"
    - /var/lib/nomad
    - /etc/nomad
  tags:
    - nomad

- name: decompress archive
  unarchive:
    src: /tmp/nomad.zip
    dest: "{{ nomad_install_path }}/{{ nomad_version }}"
    copy: no

- name: link the versioned nomad to the local bin
  file:
    src: "{{ nomad_install_path }}/{{ nomad_version }}/nomad"
    dest: /usr/local/bin/nomad
    owner: root
    group: root
    state: link
  tags:
    - nomad

- name: remove the temp archives
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /tmp/nomad.zip
  tags:
    - nomad

- name: setup nomad server config
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 644
  with_items:
    - src: server.conf.j2
      dest: /etc/nomad/nomad.hcl
  tags:
    - nomad

- name: install nomad systemd unit
  copy:
    src: nomad.service
    dest: "{{ systemd_dir }}/nomad.service"
  notify:
    - reload systemd
  tags:
    - nomad

- name: enable nomad
  service:
    name: nomad
    enabled: yes
    state: started
  tags:
    - nomad
